# Generated by Django 5.0 on 2024-08-23 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advlink',
            name='shorten_url',
        ),
    ]
